name: ktlint

on:
  pull_request:
    paths:
      - '.github/workflows/ktlint.yml'
      - 'src/**/*.kt'
      - '**.kts'
      - '.editorconfig'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.3.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true
      - uses: yutailang0119/action-ktlint@v4
        with:
          report-path: build/ktlint-report.xml
          ignore-warnings: false
        continue-on-error: false
